[cmake]
version = "3.15"

[project]
name = "cf_tracer"

[fetch-content.zydis]
git = "https://github.com/zyantific/zydis"
tag = "v4.1.0"

[fetch-content.eeh]
git = "https://github.com/mattrwx/Early-Exception-Handling"
tag = "main"

[target.tracer]
type = "shared"
sources = ["src/dllmain.cpp", "src/cft.cpp", "src/dumper.cpp", "${eeh_SOURCE_DIR}/eeh.cpp"]
compile-features = ["cxx_std_23"]
include-directories = ["${eeh_SOURCE_DIR}"]
link-libraries = ["Zydis", "ntdll"]

[target.tracer.properties]
OUTPUT_NAME = "tracer"
PREFIX = ""